@ECHO OFF
SET /P A = "INPUT A "
SET /P B = "INPUT B "
IF (%A% == %B%) (
ECHO "THE NUMBERS ARE EQUAL" 
GOTO EXIT)
IF (%A% LSS %B%) (
ECHO "THE FIRST NUMBER IS BIGGER THAN SECOND ONE"
GOTO EXIT)
ELSE (
ECHO "THE SECOND NUMBER IS BIGGER THAN FIRST ONE"
GOTO EXIT)
:EXIT
PAUSE